[package]
name = "lw-lwnx"
version = "0.1.0"
edition = "2021"

[features]
default = []

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["impl-default", "ioapiset"] }

[target.'cfg(unix)'.dependencies]
serialport = "4"